### ISSUE TITLE
size

### ISSUE THREAD

**Issue by dollar-cat** [dtilhoo/ripple_wave#2]
The waviness displayed on the tablet is particularly large, occupying nearly 50% of my height. What should I do to make it more adaptive in width and height

**Comment by dollar-cat** [comment]
The ripples display perfectly on the phone, but appear particularly high on the tablet, occupying most of the space

**Comment by dtilhoo** [comment]
@dollar-cat  if you wrap it with a sizedbox and define the height and width you want for the tablet? you can use a helper to know if you're on tablet and enable the sizedbox in this case. try it and let me know

**Comment by dollar-cat** [comment]
ok

**Comment by dollar-cat** [comment]
I used sizedbox to wrap the ripple size unchanged, but it is still relatively large

**Comment by dtilhoo** [comment]
what are you using as child of the ripple wave? is it an icon? you can resize the size of the icon for tablet screen
